config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :commerical_units, path: "commerical", only: %i[new create]
  resources :complex_buildings, path: "complexbuildings", only: %i[new create]
  resources :houses, only: %i[new create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/asset.rb
class Asset < ApplicationRecord
  belongs_to :assetable, polymorphic: true

  delegate :image, to: :assetable
end

app/models/commerical_unit.rb
class CommericalUnit < ApplicationRecord
  validates :parking, presence: true
  validates :shops, presence: true

  has_one_attached :image
end

app/models/complex_building.rb
class ComplexBuilding < ApplicationRecord
  validates :units, presence: true

  has_one_attached :image
end

app/models/house.rb
class House < ApplicationRecord
  has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/commerical_units_controller.rb
class CommericalUnitsController < ApplicationController
  before_action :set_commerical_unit, only: %i[ show edit update destroy ]

  # GET /commerical_units or /commerical_units.json
  def index
    @commerical_units = CommericalUnit.all
  end

  # GET /commerical_units/new
  def new
    @commerical_unit = CommericalUnit.new
  end

  # POST /commerical_units or /commerical_units.json
  def create
    @asset = Asset.new(asset_params)
    @commerical_unit = CommericalUnit.new(commerical_unit_params)

    @asset.assetable = @commerical_unit

    respond_to do |format|
      if @commerical_unit.save
        @asset.save
        format.html { redirect_to root_path, notice: "Commerical unit was successfully created." }
        format.json { render :show, status: :created, location: @commerical_unit }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @commerical_unit.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_commerical_unit
    @commerical_unit = CommericalUnit.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def commerical_unit_params
    params.require(:commerical_unit).permit(:shops, :parking, :image)
  end

  def asset_params
    params.require(:commerical_unit).permit(:owner, :address, :sqmt, :price)
  end
end

app/controllers/complex_buildings_controller.rb
class ComplexBuildingsController < ApplicationController
  before_action :set_complex_building, only: %i[ show edit update destroy ]

  # GET /complex_buildings or /complex_buildings.json
  def index
    @complex_buildings = ComplexBuilding.all
  end

  # GET /complex_buildings/new
  def new
    @complex_building = ComplexBuilding.new
  end

  # POST /complex_buildings or /complex_buildings.json
  def create
    @complex_building = ComplexBuilding.new(complex_building_params)

    respond_to do |format|
      if @complex_building.save
        format.html { redirect_to root_path, notice: "Complex building was successfully created." }
        format.json { render :show, status: :created, location: @complex_building }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @complex_building.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_complex_building
    @complex_building = ComplexBuilding.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def complex_building_params
    params.require(:complex_building).permit(:owner, :address, :units, :sqmt, :price, :image)
  end

  def asset_params
    params.require(:house).permit(:owner, :address, :sqmt, :price)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @all = Asset.order :created_at

    @houses = House.order :created_at
    @complex_buildings = ComplexBuilding.order :created_at
    @commerical_units = CommericalUnit.order :created_at
  end
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  before_action :set_house, only: %i[ show edit update destroy ]

  # GET /houses or /houses.json
  def index
    @houses = House.all
  end

  # GET /houses/new
  def new
    @house = House.new
  end

  # POST /houses or /houses.json
  def create
    @house = House.new(house_params)
    @asset = Asset.new(asset_params)

    @asset.assetable = @house

    respond_to do |format|
      if @house.save
        @asset.save
        format.html { redirect_to root_path, notice: "House was successfully created." }
        format.json { render :show, status: :created, location: @house }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_house
    @house = House.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def house_params
    params.require(:house).permit(:rooms, :floors, :air_cond, :image)
  end

  def asset_params
    params.require(:house).permit(:owner, :address, :sqmt, :price)
  end
end

app/controllers/purchase_assets_controller.rb
class PurchaseAssetsController < ApplicationController
  def create
    VeryLongTaskJob.perform_now from: params[:owner], to: params[:buyer]
    redirect_to root_path, notice: "You Have purchased this asset successfully"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/commerical_units_helper.rb
module CommericalUnitsHelper
end

app/helpers/complex_buildings_helper.rb
module ComplexBuildingsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/helpers/purchase_assets_helper.rb
module PurchaseAssetsHelper
end

app/views/assets/_asset.html.erb
<article class="w-3/12 p-4 my-2 mx-10 bg-white rounded-lg shadow border border-primary">
  <header class="mb-2">
    <h2 class="text-xl color-primary">Owner: <%= asset.owner %></h2>
  </header>

  <%= image_tag asset.image, class: "w-full h-48 rounded-md", alt: "An image that is associated with this asset" %>

  <main class="my-2">
    <section class="w-full flex justify-between items-center mb-2 ">
      <h1 class="text-xl color-secondary">Type: <%= asset.assetable.class.name.demodulize %></h1>

      <span class="font-medium text-gray-400">Area: <%= asset.sqmt %></span>
    </section>

    <%= render asset.assetable, locals: {"#{asset.assetable.class}": asset.assetable} %>
  </main>

  <footer class="flex w-full justify-between items-center my-2">
    <div>
      <span class="color-secondary">Price: </span>
      <span class="font-medium text-gray-400"><%= asset.price %></span>
    </div>

    <div>
      <button class="bg-primary rounded-md text-white text-md px-2 py-1 ">
        Buy
      </button>
    </div>
  </footer>
</article>

app/views/commerical_units/_commerical_unit.html.erb
<section class="w-full my-2 text-gray-600">

  <p>Parking: <span><%= commerical_unit.parking %></span></p>
  <p>No. Of Shops: <span><%= commerical_unit.shops %></span></p>

</section>

app/views/commerical_units/_form.html.erb
<%= form_with(model: commerical_unit, local: true, class: "w-6/12 rounded-md shadow border border-primary p-4 bg-white flex flex-col justify-center items-center") do |form| %>
  <% if commerical_unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(commerical_unit.errors.count, "error") %> prohibited this commerical_unit from being saved:</h2>

      <ul>
        <% commerical_unit.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <header>
    <h1 class="text--green font-medium text-2xl">Add a new commercial unit</h1>
  </header>

  <div class="w-8/12 flex flex-col justify-center">

    <div class="w-full flex flex-col my-2">
      <%= form.label :owner %>
      <%= form.text_field :owner %>
    </div>

    <div class="w-full flex flex-col my-2">
      <%= form.label :address %>
      <%= form.email_field :address %>
    </div>

    <div class="w-full flex flex-col my-2">
      <%= form.label :shops %>
      <%= form.number_field :shops %>
    </div>

    <div class="w-full flex flex-col my-2">
      <%= form.label :sqmt %>
      <%= form.number_field :sqmt %>
    </div>

    <div class="w-full flex flex-col my-2">
      <%= form.label :parking %>
      <%= form.number_field :parking %>
    </div>

    <div class="w-full flex flex-col my-2">
      <%= form.label :price %>
      <%= form.text_field :price %>
    </div>

    <div class="w-full flex flex-col my-2">
      <%= form.label :image %>
      <%= form.file_field :image %>
    </div>

    <div class="actions">
      <button class="bg-primary text-base my-2 text-white rounded-md px-4 py-2">Add new commercial unit</button>
    </div>
  </div>
<% end %>

app/views/commerical_units/edit.html.erb
<h1>Editing Commerical Unit</h1>

<%= render 'form', commerical_unit: @commerical_unit %>

<%= link_to 'Show', @commerical_unit %> |
<%= link_to 'Back', commerical_units_path %>

app/views/commerical_units/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Commerical Units</h1>

<table>
  <thead>
    <tr>
      <th>Owner</th>
      <th>Address</th>
      <th>Shops</th>
      <th>Sqmt</th>
      <th>Parking</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @commerical_units.each do |commerical_unit| %>
      <tr>
        <td><%= commerical_unit.owner %></td>
        <td><%= commerical_unit.address %></td>
        <td><%= commerical_unit.shops %></td>
        <td><%= commerical_unit.sqmt %></td>
        <td><%= commerical_unit.parking %></td>
        <td><%= commerical_unit.price %></td>
        <td><%= link_to 'Show', commerical_unit %></td>
        <td><%= link_to 'Edit', edit_commerical_unit_path(commerical_unit) %></td>
        <td><%= link_to 'Destroy', commerical_unit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Commerical Unit', new_commerical_unit_path %>

app/views/commerical_units/new.html.erb
<h1>New Commerical Unit</h1>

<%= render 'form', commerical_unit: @commerical_unit %>

<%= link_to 'Back', commerical_units_path %>

app/views/commerical_units/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Owner:</strong>
  <%= @commerical_unit.owner %>
</p>

<p>
  <strong>Address:</strong>
  <%= @commerical_unit.address %>
</p>

<p>
  <strong>Shops:</strong>
  <%= @commerical_unit.shops %>
</p>

<p>
  <strong>Sqmt:</strong>
  <%= @commerical_unit.sqmt %>
</p>

<p>
  <strong>Parking:</strong>
  <%= @commerical_unit.parking %>
</p>

<p>
  <strong>Price:</strong>
  <%= @commerical_unit.price %>
</p>

<%= link_to 'Edit', edit_commerical_unit_path(@commerical_unit) %> |
<%= link_to 'Back', commerical_units_path %>

app/views/complex_buildings/_complex_building.html.erb
<section class="w-full my-2 text-gray-600">
  <p>Floors: <span><%= building.floors %></span></p>
</section>

app/views/complex_buildings/_form.html.erb
<%= form_with(model: complex_building, local: true, class: "w-6/12 rounded-md shadow border border-primary p-4 bg-white flex flex-col justify-center items-center") do |form| %>
  <% if complex_building.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(complex_building.errors.count, "error") %> prohibited this complex_building from being saved:</h2>

      <ul>
        <% complex_building.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <header>
    <h1 class="text--green font-medium text-2xl">Add a new complex building</h1>
  </header>
  <div class="w-8/12 flex flex-col items-center">
    <div class="w-full flex flex-col my-2">
      <%= form.label :owner %>
      <%= form.text_field :owner %>
    </div>

    <div class="w-full flex flex-col my-2">
      <%= form.label :address %>
      <%= form.email_field :address %>
    </div>

    <div class="w-full flex flex-col my-2">
      <%= form.label :units %>
      <%= form.number_field :units %>
    </div>

    <div class="w-full flex flex-col my-2">
      <%= form.label :sqmt %>
      <%= form.number_field :sqmt %>
    </div>

    <div class="w-full flex flex-col my-2">
      <%= form.label :price %>
      <%= form.text_field :price %>
    </div>


    <div class="w-full flex flex-col my-2">
      <%= form.label :image %>
      <%= form.file_field :image %>
    </div>
    <div class="actions">
      <button class="bg-primary text-base my-2 text-white rounded-md">Add new complex building</button>
    </div>
  </div>
<% end %>

app/views/complex_buildings/edit.html.erb
<h1>Editing Complex Building</h1>

<%= render 'form', complex_building: @complex_building %>

<%= link_to 'Show', @complex_building %> |
<%= link_to 'Back', complex_buildings_path %>

app/views/complex_buildings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Complex Buildings</h1>

<table>
  <thead>
    <tr>
      <th>Owner</th>
      <th>Address</th>
      <th>Units</th>
      <th>Sqmt</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @complex_buildings.each do |complex_building| %>
      <tr>
        <td><%= complex_building.owner %></td>
        <td><%= complex_building.address %></td>
        <td><%= complex_building.units %></td>
        <td><%= complex_building.sqmt %></td>
        <td><%= complex_building.price %></td>
        <td><%= link_to 'Show', complex_building %></td>
        <td><%= link_to 'Edit', edit_complex_building_path(complex_building) %></td>
        <td><%= link_to 'Destroy', complex_building, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Complex Building', new_complex_building_path %>

app/views/complex_buildings/new.html.erb
<h1>New Complex Building</h1>

<%= render 'form', complex_building: @complex_building %>

<%= link_to 'Back', complex_buildings_path %>

app/views/complex_buildings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Owner:</strong>
  <%= @complex_building.owner %>
</p>

<p>
  <strong>Address:</strong>
  <%= @complex_building.address %>
</p>

<p>
  <strong>Units:</strong>
  <%= @complex_building.units %>
</p>

<p>
  <strong>Sqmt:</strong>
  <%= @complex_building.sqmt %>
</p>

<p>
  <strong>Price:</strong>
  <%= @complex_building.price %>
</p>

<%= link_to 'Edit', edit_complex_building_path(@complex_building) %> |
<%= link_to 'Back', complex_buildings_path %>

app/views/home/index.html.erb
<header class="text-left w-full px-10">
  <h1 class="text-gray-600 text-3xl font-medium">Welcome back, here are our latest places</h1>
</header>

<section class="w-full px-10 flex flex-wrap justify-center items-center flex-col">
    <main class="w-9/12 flex">
      <%= render @all %>
    </main>
</section>

app/views/houses/_form.html.erb
<%= form_with(model: house, local: true, class: "w-6/12 rounded-md shadow border border-primary p-4 bg-white flex flex-col justify-center items-center") do |form| %>
  <% if house.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(house.errors.count, "error") %> prohibited this house from being saved:</h2>

      <ul>
        <% house.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <header class="text-left">
    <h1 class="text--green font-medium text-2xl">Add a new house</h1>
  </header>

  <div class="w-8/12 flex flex-col justify-center">
    <div class="w-full flex flex-col my-2">
      <%= form.label :owner %>
      <%= form.text_field :owner %>
    </div>

    <div class="w-full flex flex-col my-2">
      <%= form.label :address, "email Address" %>
      <%= form.text_field :address %>
    </div>

    <div class="w-full flex flex-col my-2">
      <%= form.label :rooms %>
      <%= form.text_field :rooms %>
    </div>

    <div class="w-full flex flex-col my-2">
      <%= form.label :sqmt %>
      <%= form.text_field :sqmt %>
    </div>

    <div class="w-full flex flex-col my-2">
      <%= form.label :floors %>
      <%= form.text_field :floors %>
    </div>

    <div class="w-full flex items-center my-2">
      <%= form.label :air_cond %>
      <%= form.check_box :air_cond, class: "w-5 mx-2" %>
    </div>

    <div class="w-full flex flex-col">
      <%= form.label :price %>
      <%= form.text_field :price %>
    </div>

    <div class="w-full flex flex-col">
      <%= form.label :image %>
      <%= form.file_field :image %>
    </div>

    <div class="actions">
      <button class="bg-primary text-base my-2 text-white px-4 py-2 rounded-md">
        Add
      </button>
    </div>
  </div>
<% end %>

app/views/houses/_house.html.erb
<section class="w-full my-2 text-gray-600">
  <div class="flex">
              <span>
                Has AC:
              </span>
    <% if house.air_cond %>
      <svg class="w-6 h-6 text--green" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"/>
      </svg>
    <% else %>
      <svg class="w-6 h-6 text-red-600" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/>
      </svg>
    <% end %>
  </div>
  <p>Floors: <span><%= house.floors %></span></p>
</section>

app/views/houses/edit.html.erb
<h1>Editing House</h1>

<%= render 'form', house: @house %>

<%= link_to 'Show', @house %> |
<%= link_to 'Back', houses_path %>

app/views/houses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Houses</h1>

<table>
  <thead>
    <tr>
      <th>Owner</th>
      <th>Address</th>
      <th>Rooms</th>
      <th>Sqmt</th>
      <th>Floors</th>
      <th>Air cond</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @houses.each do |house| %>
      <tr>
        <td><%= house.owner %></td>
        <td><%= house.address %></td>
        <td><%= house.rooms %></td>
        <td><%= house.sqmt %></td>
        <td><%= house.floors %></td>
        <td><%= house.air_cond %></td>
        <td><%= house.price %></td>
        <td><%= link_to 'Show', house %></td>
        <td><%= link_to 'Edit', edit_house_path(house) %></td>
        <td><%= link_to 'Destroy', house, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New House', new_house_path %>

app/views/houses/new.html.erb
<section class="w-full flex flex-col justify-center items-center p-2">
  <%= render 'form', house: @house %>

  <%= link_to 'Back', root_path, class: "color-tertiary" %>
</section>

app/views/houses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Owner:</strong>
  <%= @house.owner %>
</p>

<p>
  <strong>Address:</strong>
  <%= @house.address %>
</p>

<p>
  <strong>Rooms:</strong>
  <%= @house.rooms %>
</p>

<p>
  <strong>Sqmt:</strong>
  <%= @house.sqmt %>
</p>

<p>
  <strong>Floors:</strong>
  <%= @house.floors %>
</p>

<p>
  <strong>Air cond:</strong>
  <%= @house.air_cond %>
</p>

<p>
  <strong>Price:</strong>
  <%= @house.price %>
</p>

<%= image_tag @house.image, class: "w-40 h-40 rounded-md" %>
<%= link_to 'Edit', edit_house_path(@house) %> |
<%= link_to 'Back', houses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RbblabTask</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body class="bg-body h-screen relative">
  <header class="bg-white px-4 py-2 mb-4 border-b border-gray-300">
    <nav class="w-full flex justify-between items-center px-2 py-2">
      <h1 class="text-2xl color-primary font-medium">
        <a href="/">RBBTask</a>
      </h1>
    </nav>

  </header>


  <div class="w-full flex flex-col justify-center items-center">
    <%= yield %>
  </div>
  </body>
</html>